export const mockBooks = [
  {
    id: 1,
    title: 'The Midnight Library',
    author: 'Matt Haig',
    authorImage: '/images/authors/matt-haig.jpg',
    authorBio: 'Matt Haig is an English author and journalist. He has written both fiction and non-fiction books for children and adults, often in the speculative fiction genre.',
    coverImage: '/images/covers/the-midnight-library.png',
    rating: 4.5,
    summary: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    publisher: 'Viking',
    pages: 304,
    duration: '8h 50m',
    comments: [
      { id: 1, author: 'Jane Doe', rating: 5, text: 'An absolutely brilliant and thought-provoking read!', date: '2023-10-26T10:00:00Z' },
    ],
    genre: 'Fiction',
  },
  {
    id: 2,
    title: 'Dune',
    author: 'Frank Herbert',
    authorImage: '/images/authors/frank-herbert.jpg',
    authorBio: 'Frank Herbert was an American science-fiction author best known for the 1965 novel Dune and its five sequels.',
    coverImage: '/images/covers/dune.png',
    rating: 4.8,
    summary: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides.',
    publisher: 'Chilton Books',
    pages: 412,
    duration: '21h 5m',
    comments: [],
    genre: 'Science Fiction',
  },
  {
    id: 3,
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    coverImage: '/images/covers/project-hail-mary.png',
    rating: 4.9,
    summary: 'Ryland Grace is the sole survivor on a desperate, last-chance mission.',
    comments: [],
    genre: 'Science Fiction',
  },
  {
    id: 4,
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    coverImage: '/images/covers/the-silent-patient.png',
    rating: 4.2,
    summary: 'Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer.',
    comments: [],
    genre: 'Thriller',
  },
  {
    id: 5,
    title: 'Educated',
    author: 'Tara Westover',
    coverImage: '/images/covers/educated.png',
    rating: 4.7,
    summary: 'A memoir about a young girl who, kept out of school, leaves her survivalist family.',
    comments: [],
    genre: 'Biography',
  },
  {
    id: 6,
    title: 'Circe',
    author: 'Madeline Miller',
    coverImage: '/images/covers/circe.png',
    rating: 4.6,
    summary: 'In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born.',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 7,
    title: 'The Vanishing Half',
    author: 'Brit Bennett',
    coverImage: '/images/covers/the-vanishing-half.png',
    rating: 4.4,
    summary: 'The Vignes twin sisters will always be identical. But after growing up together in a small, southern black community...',
    comments: [],
    genre: 'Fiction',
  },
  {
    id: 8,
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    coverImage: '/images/covers/sapiens.png',
    rating: 4.8,
    summary: '100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us.',
    comments: [],
    genre: 'History',
  },
  {
    id: 9,
    title: 'Atomic Habits',
    author: 'James Clear',
    coverImage: '/images/covers/atomic-habits.png',
    rating: 4.9,
    summary: 'An easy and proven way to build good habits and break bad ones.',
    comments: [],
    genre: 'Self-Help',
  },
  {
    id: 10,
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    coverImage: '/images/covers/the-seven-husbands-of-evelyn-hugo.png',
    rating: 4.7,
    summary: 'Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth.',
    comments: [],
    genre: 'Romance',
  },
  {
    id: 11,
    title: 'The Song of Achilles',
    author: 'Madeline Miller',
    coverImage: '/images/covers/the-song-of-achilles.png',
    rating: 4.8,
    summary: 'A tale of gods, kings, immortal fame, and the human heart.',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 12,
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    coverImage: '/images/covers/klara-and-the-sun.png',
    rating: 4.3,
    summary: 'A novel that looks at our changing world through the eyes of an unforgettable narrator.',
    comments: [],
    genre: 'Science Fiction',
  },
  {
    id: 13,
    title: 'The Four Winds',
    author: 'Kristin Hannah',
    coverImage: '/images/covers/the-four-winds.png',
    rating: 4.5,
    summary: 'An epic novel of love and heroism and hope, set during the Great Depression.',
    comments: [],
    genre: 'History',
  },
  {
    id: 14,
    title: 'The Guest List',
    author: 'Lucy Fokley',
    coverImage: '/images/covers/the-guest-list.png',
    rating: 4.1,
    summary: 'A wedding celebration turns dark and deadly in this deliciously wicked and atmospheric thriller.',
    comments: [],
    genre: 'Thriller',
  },
  {
    id: 15,
    title: 'Becoming',
    author: 'Michelle Obama',
    coverImage: '/images/covers/becoming.png',
    rating: 4.9,
    summary: 'A deeply personal reckoning of a woman of soul and substance who has steadily defied expectations.',
    comments: [],
    genre: 'Biography',
  },
  {
    id: 16,
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    coverImage: '/images/covers/where-the-crawdads-sing.png',
    rating: 4.6,
    summary: 'A heartbreaking coming-of-age story and a surprising tale of possible murder.',
    comments: [],
    genre: 'Fiction',
  },
  {
    id: 17,
    title: 'The Martian',
    author: 'Andy Weir',
    coverImage: '/images/covers/the-martian.png',
    rating: 4.7,
    summary: 'An astronaut\'s struggle to survive on Mars after being left behind by his crew.',
    comments: [],
    genre: 'Science Fiction',
  },
  {
    id: 18,
    title: 'The Night Circus',
    author: 'Erin Morgenstern',
    coverImage: '/images/covers/the-night-circus.png',
    rating: 4.5,
    summary: 'A magical competition between two young illusionists, set in a mysterious circus.',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 19,
    title: 'Verity',
    author: 'Colleen Hoover',
    coverImage: '/images/covers/verity.png',
    rating: 4.4,
    summary: 'A struggling writer accepts a job offer that will change her life forever.',
    comments: [],
    genre: 'Thriller',
  },
  {
    id: 20,
    title: 'A Man Called Ove',
    author: 'Fredrik Backman',
    coverImage: '/images/covers/a-man-called-ove.png',
    rating: 4.6,
    summary: 'A grumpy yet loveable man finds his solitary world turned on its head when a young family moves in next door.',
    comments: [],
    genre: 'Fiction',
  },
  {
    id: 21,
    title: 'The Lincoln Highway',
    author: 'Amor Towles',
    coverImage: '/images/covers/the-lincoln-highway.png',
    rating: 4.5,
    summary: 'A story of four boys on a fateful journey from Nebraska to New York City in 1954.',
    comments: [],
    genre: 'History',
  },
  {
    id: 22,
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    coverImage: '/images/covers/the-power-of-now.png',
    rating: 4.7,
    summary: 'A guide to spiritual enlightenment, focusing on the importance of living in the present moment.',
    comments: [],
    genre: 'Self-Help',
  },
  {
    id: 23,
    title: 'Red, White & Royal Blue',
    author: 'Casey McQuiston',
    coverImage: '/images/covers/red-white-royal-blue.png',
    rating: 4.4,
    summary: 'The First Son falls in love with a British prince, creating a diplomatic and media frenzy.',
    comments: [],
    genre: 'Romance',
  },
  {
    id: 24,
    title: 'The House in the Cerulean Sea',
    author: 'T.J. Klune',
    coverImage: '/images/covers/the-house-in-the-cerulean-sea.png',
    rating: 4.8,
    summary: 'A social worker is sent to a magical orphanage to determine if the children there are a threat to the world.',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 25,
    title: 'Anxious People',
    author: 'Fredrik Backman',
    coverImage: '/images/covers/anxious-people.png',
    rating: 4.5,
    summary: 'A poignant comedy about a crime that never took place, a would-be bank robber who disappears into thin air, and eight extremely anxious strangers who find they have more in common than they ever imagined.',
    comments: [],
    genre: 'Fiction',
  }
];

export const mockGenres = ['Fiction', 'Science Fiction', 'Fantasy', 'Mystery', 'Thriller', 'Romance', 'Biography', 'History', 'Self-Help'];