export const mockBooks = [
  {
    id: 1,
    title: 'The Midnight Library',
    author: 'Matt Haig',
    authorImage: '/images/authors/matt-haig.jpg',
    authorBio: 'Matt Haig is an English author and journalist. He has written both fiction and non-fiction books for children and adults, often in the speculative fiction genre.',
    coverImage: '/images/covers/the-midnight-library.png',
    rating: 4.5,
    summary: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    publisher: 'Viking',
    pages: 304,
    duration: '8h 50m',
    comments: [
      { id: 1, author: 'Jane Doe', rating: 5, text: 'An absolutely brilliant and thought-provoking read!', date: '2023-10-26T10:00:00Z' },
    ],
    genre: 'Fiction',
  },
  {
    id: 2,
    title: 'Dune',
    author: 'Frank Herbert',
    authorImage: '/images/authors/frank-herbert.jpg',
    authorBio: 'Frank Herbert was an American science-fiction author best known for the 1965 novel Dune and its five sequels.',
    coverImage: '/images/covers/dune.png',
    rating: 4.8,
    summary: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides.',
    publisher: 'Chilton Books',
    pages: 412,
    duration: '21h 5m',
    comments: [],
    genre: 'Science Fiction',
  },
  {
    id: 3,
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    authorImage: '/images/authors/andy-weir.jpg',
    authorBio: 'Andy Weir is an American novelist and software engineer. He is best known for his debut novel, The Martian.',
    coverImage: '/images/covers/project-hail-mary.png',
    rating: 4.9,
    summary: 'Ryland Grace is the sole survivor on a desperate, last-chance mission.',
    publisher: 'Ballantine Books',
    pages: 496,
    duration: '16h 10m',
    comments: [],
    genre: 'Science Fiction',
  },
  {
    id: 4,
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    authorImage: '/images/authors/alex-michaelides.jpg',
    authorBio: 'Alex Michaelides is a bestselling British-Cypriot author and screenwriter.',
    coverImage: '/images/covers/the-silent-patient.png',
    rating: 4.2,
    summary: 'Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer.',
    publisher: 'Celadon Books',
    pages: 336,
    duration: '8h 43m',
    comments: [],
    genre: 'Thriller',
  },
  {
    id: 5,
    title: 'Educated',
    author: 'Tara Westover',
    authorImage: '/images/authors/tara-westover.jpg',
    authorBio: 'Tara Westover is an American memoirist, essayist and historian.',
    coverImage: '/images/covers/educated.png',
    rating: 4.7,
    summary: 'A memoir about a young girl who, kept out of school, leaves her survivalist family.',
    publisher: 'Random House',
    pages: 352,
    duration: '12h 10m',
    comments: [],
    genre: 'Biography',
  },
  {
    id: 6,
    title: 'Circe',
    author: 'Madeline Miller',
    authorImage: '/images/authors/madeline-miller.jpg',
    authorBio: 'Madeline Miller is an American novelist, author of The Song of Achilles and Circe.',
    coverImage: '/images/covers/circe.png',
    rating: 4.6,
    summary: 'In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born.',
    publisher: 'Little, Brown and Company',
    pages: 393,
    duration: '12h 8m',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 7,
    title: 'The Vanishing Half',
    author: 'Brit Bennett',
    authorImage: '/images/authors/brit-bennett.jpg',
    authorBio: 'Brit Bennett is an American writer based in Los Angeles.',
    coverImage: '/images/covers/the-vanishing-half.png',
    rating: 4.4,
    summary: 'The Vignes twin sisters will always be identical. But after growing up together in a small, southern black community...',
    publisher: 'Riverhead Books',
    pages: 352,
    duration: '11h 34m',
    comments: [],
    genre: 'Fiction',
  },
  {
    id: 8,
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    authorImage: '/images/authors/yuval-noah-harari.jpg',
    authorBio: 'Yuval Noah Harari is an Israeli public intellectual, historian and a professor in the Department of History at the Hebrew University of Jerusalem.',
    coverImage: '/images/covers/sapiens.png',
    rating: 4.8,
    summary: '100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us.',
    publisher: 'Harvill Secker',
    pages: 443,
    duration: '15h 17m',
    comments: [],
    genre: 'History',
  },
  {
    id: 9,
    title: 'Atomic Habits',
    author: 'James Clear',
    authorImage: '/images/authors/james-clear.jpg',
    authorBio: 'James Clear is an American author, speaker, and photographer.',
    coverImage: '/images/covers/atomic-habits.png',
    rating: 4.9,
    summary: 'An easy and proven way to build good habits and break bad ones.',
    publisher: 'Avery',
    pages: 320,
    duration: '5h 35m',
    comments: [],
    genre: 'Self-Help',
  },
  {
    id: 10,
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    authorImage: '/images/authors/taylor-jenkins-reid.jpg',
    authorBio: 'Taylor Jenkins Reid is an American author, producer and screenwriter.',
    coverImage: '/images/covers/the-seven-husbands-of-evelyn-hugo.png',
    rating: 4.7,
    summary: 'Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth.',
    publisher: 'Atria Books',
    pages: 389,
    duration: '12h 10m',
    comments: [],
    genre: 'Romance',
  },
  {
    id: 11,
    title: 'The Song of Achilles',
    author: 'Madeline Miller',
    authorImage: '/images/authors/madeline-miller.jpg',
    authorBio: 'Madeline Miller is an American novelist, author of The Song of Achilles and Circe.',
    coverImage: '/images/covers/the-song-of-achilles.png',
    rating: 4.8,
    summary: 'A tale of gods, kings, immortal fame, and the human heart.',
    publisher: 'Ecco',
    pages: 352,
    duration: '11h 5m',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 12,
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    authorImage: '/images/authors/kazuo-ishiguro.jpg',
    authorBio: 'Kazuo Ishiguro is a British novelist, screenwriter, and short-story writer.',
    coverImage: '/images/covers/klara-and-the-sun.png',
    rating: 4.3,
    summary: 'A novel that looks at our changing world through the eyes of an unforgettable narrator.',
    publisher: 'Faber & Faber',
    pages: 307,
    duration: '10h 2m',
    comments: [],
    genre: 'Science Fiction',
  },
  {
    id: 13,
    title: 'The Four Winds',
    author: 'Kristin Hannah',
    authorImage: '/images/authors/kristin-hannah.jpg',
    authorBio: 'Kristin Hannah is an American writer.',
    coverImage: '/images/covers/the-four-winds.png',
    rating: 4.5,
    summary: 'An epic novel of love and heroism and hope, set during the Great Depression.',
    publisher: 'St. Martin\'s Press',
    pages: 464,
    duration: '15h 3m',
    comments: [],
    genre: 'History',
  },
  {
    id: 14,
    title: 'The Guest List',
    author: 'Lucy Fokley',
    authorImage: '/images/authors/lucy-fokley.jpg',
    authorBio: 'Lucy Fokley is a British author of mystery novels.',
    coverImage: '/images/covers/the-guest-list.png',
    rating: 4.1,
    summary: 'A wedding celebration turns dark and deadly in this deliciously wicked and atmospheric thriller.',
    publisher: 'William Morrow',
    pages: 320,
    duration: '10h 1m',
    comments: [],
    genre: 'Thriller',
  },
  {
    id: 15,
    title: 'Becoming',
    author: 'Michelle Obama',
    authorImage: '/images/authors/michelle-obama.jpg',
    authorBio: 'Michelle Obama is an American attorney and author who was the first lady of the United States from 2009 to 2017.',
    coverImage: '/images/covers/becoming.png',
    rating: 4.9,
    summary: 'A deeply personal reckoning of a woman of soul and substance who has steadily defied expectations.',
    publisher: 'Crown',
    pages: 426,
    duration: '19h 3m',
    comments: [],
    genre: 'Biography',
  },
  {
    id: 16,
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    authorImage: '/images/authors/delia-owens.jpg',
    authorBio: 'Delia Owens is an American author and zoologist.',
    coverImage: '/images/covers/where-the-crawdads-sing.png',
    rating: 4.6,
    summary: 'A heartbreaking coming-of-age story and a surprising tale of possible murder.',
    publisher: 'G.P. Putnam\'s Sons',
    pages: 384,
    duration: '12h 27m',
    comments: [],
    genre: 'Fiction',
  },
  {
    id: 17,
    title: 'The Martian',
    author: 'Andy Weir',
    authorImage: '/images/authors/andy-weir.jpg',
    authorBio: 'Andy Weir is an American novelist and software engineer. He is best known for his debut novel, The Martian.',
    coverImage: '/images/covers/the-martian.png',
    rating: 4.7,
    summary: 'An astronaut\'s struggle to survive on Mars after being left behind by his crew.',
    publisher: 'Crown Publishing Group',
    pages: 384,
    duration: '11h 4m',
    comments: [],
    genre: 'Science Fiction',
  },
  {
    id: 18,
    title: 'The Night Circus',
    author: 'Erin Morgenstern',
    authorImage: '/images/authors/erin-morgenstern.jpg',
    authorBio: 'Erin Morgenstern is an American writer and artist.',
    coverImage: '/images/covers/the-night-circus.png',
    rating: 4.5,
    summary: 'A magical competition between two young illusionists, set in a mysterious circus.',
    publisher: 'Doubleday',
    pages: 391,
    duration: '13h 43m',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 19,
    title: 'Verity',
    author: 'Colleen Hoover',
    authorImage: '/images/authors/colleen-hoover.jpg',
    authorBio: 'Colleen Hoover is an American author who primarily writes novels in the romance and young adult fiction genres.',
    coverImage: '/images/covers/verity.png',
    rating: 4.4,
    summary: 'A struggling writer accepts a job offer that will change her life forever.',
    publisher: 'Grand Central Publishing',
    pages: 336,
    duration: '9h 27m',
    comments: [],
    genre: 'Thriller',
  },
  {
    id: 20,
    title: 'A Man Called Ove',
    author: 'Fredrik Backman',
    authorImage: '/images/authors/fredrik-backman.jpg',
    authorBio: 'Fredrik Backman is a Swedish columnist, blogger and writer.',
    coverImage: '/images/covers/a-man-called-ove.png',
    rating: 4.6,
    summary: 'A grumpy yet loveable man finds his solitary world turned on its head when a young family moves in next door.',
    publisher: 'Atria Books',
    pages: 337,
    duration: '9h 10m',
    comments: [],
    genre: 'Fiction',
  },
  {
    id: 21,
    title: 'The Lincoln Highway',
    author: 'Amor Towles',
    authorImage: '/images/authors/amor-towles.jpg',
    authorBio: 'Amor Towles is an American novelist.',
    coverImage: '/images/covers/the-lincoln-highway.png',
    rating: 4.5,
    summary: 'A story of four boys on a fateful journey from Nebraska to New York City in 1954.',
    publisher: 'Viking',
    pages: 576,
    duration: '18h 3m',
    comments: [],
    genre: 'History',
  },
  {
    id: 22,
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    authorImage: '/images/authors/eckhart-tolle.jpg',
    authorBio: 'Eckhart Tolle is a spiritual teacher and self-help author.',
    coverImage: '/images/covers/the-power-of-now.png',
    rating: 4.7,
    summary: 'A guide to spiritual enlightenment, focusing on the importance of living in the present moment.',
    publisher: 'New World Library',
    pages: 236,
    duration: '8h 11m',
    comments: [],
    genre: 'Self-Help',
  },
  {
    id: 23,
    title: 'Red, White & Royal Blue',
    author: 'Casey McQuiston',
    authorImage: '/images/authors/casey-mcquiston.jpg',
    authorBio: 'Casey McQuiston is an American author of romance novels.',
    coverImage: '/images/covers/red-white-royal-blue.png',
    rating: 4.4,
    summary: 'The First Son falls in love with a British prince, creating a diplomatic and media frenzy.',
    publisher: 'St. Martin\'s Griffin',
    pages: 421,
    duration: '12h 15m',
    comments: [],
    genre: 'Romance',
  },
  {
    id: 24,
    title: 'The House in the Cerulean Sea',
    author: 'T.J. Klune',
    authorImage: '/images/authors/tj-klune.jpg',
    authorBio: 'TJ Klune is an American author of fantasy and romance novels.',
    coverImage: '/images/covers/the-house-in-the-cerulean-sea.png',
    rating: 4.8,
    summary: 'A social worker is sent to a magical orphanage to determine if the children there are a threat to the world.',
    publisher: 'Tor Books',
    pages: 394,
    duration: '12h 12m',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 25,
    title: 'Anxious People',
    author: 'Fredrik Backman',
    authorImage: '/images/authors/fredrik-backman.jpg',
    authorBio: 'Fredrik Backman is a Swedish columnist, blogger and writer.',
    coverImage: '/images/covers/anxious-people.png',
    rating: 4.5,
    summary: 'A poignant comedy about a crime that never took place, a would-be bank robber who disappears into thin air, and eight extremely anxious strangers who find they have more in common than they ever imagined.',
    publisher: 'Atria Books',
    pages: 341,
    duration: '10h 5m',
    comments: [],
    genre: 'Fiction',
  }
];

export const mockGenres = ['Fiction', 'Science Fiction', 'Fantasy', 'Mystery', 'Thriller', 'Romance', 'Biography', 'History', 'Self-Help'];