export const mockBooks = [
  {
    id: 1,
    title: 'The Midnight Library',
    author: 'Matt Haig',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1602190253l/52578297.jpg',
    rating: 4.5,
    summary: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different, if you had the chance to undo your regrets?',
    comments: [
      { id: 1, author: 'Jane Doe', rating: 5, text: 'An absolutely brilliant and thought-provoking read!', date: '2023-10-26T10:00:00Z' },
      { id: 2, author: 'John Smith', rating: 4, text: 'A very unique concept. I enjoyed it, though the ending felt a bit rushed.', date: '2023-10-25T14:30:00Z' },
    ],
    genre: 'Fiction',
  },
  {
    id: 2,
    title: 'Dune',
    author: 'Frank Herbert',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1555447414l/44767458.jpg',
    rating: 4.8,
    summary: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange, a drug capable of extending life and enhancing consciousness.',
    comments: [],
    genre: 'Science Fiction',
  },
  // Add more books...
  {
    id: 3,
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1597695864l/54424021.jpg',
    rating: 4.9,
    summary: 'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn’t know that. He can’t even remember his own name, let alone the nature of his assignment or how to complete it.',
    comments: [
       { id: 1, author: 'Emily White', rating: 5, text: 'Absolutely captivating from start to finish. A must-read for sci-fi fans.', date: '2023-11-01T11:00:00Z' }
    ],
    genre: 'Science Fiction',
  },
  {
    id: 4,
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/40097951.jpg',
    rating: 4.2,
    summary: 'Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London’s most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.',
    comments: [],
    genre: 'Thriller',
  },
  {
    id: 5,
    title: 'Educated',
    author: 'Tara Westover',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1506026634l/35133922.jpg',
    rating: 4.7,
    summary: 'A memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    comments: [],
    genre: 'Biography',
  },
  {
    id: 6,
    title: 'Circe',
    author: 'Madeline Miller',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1565909496l/35959740.jpg',
    rating: 4.6,
    summary: 'In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child--not powerful, like her father, nor viciously alluring like her mother. Turning to the world of mortals for companionship, she discovers that she does possess power--the power of witchcraft, which can transform rivals into monsters and menace the gods themselves.',
    comments: [],
    genre: 'Fantasy',
  },
  {
    id: 7,
    title: 'The Vanishing Half',
    author: 'Brit Bennett',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1578334943l/51791252.jpg',
    rating: 4.4,
    summary: 'The Vignes twin sisters will always be identical. But after growing up together in a small, southern black community and running away at age sixteen, it\'s not just the shape of their daily lives that is different as adults, it\'s everything: their families, their communities, their racial identities.',
    comments: [],
    genre: 'Fiction',
  },
  {
    id: 8,
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1420585954l/23692271.jpg',
    rating: 4.8,
    summary: '100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. Homo sapiens. How did our species succeed in the battle for dominance? Why did our foraging ancestors come together to create cities and kingdoms? How did we come to believe in gods, nations and human rights?',
    comments: [],
    genre: 'History',
  },
  {
    id: 9,
    title: 'Atomic Habits',
    author: 'James Clear',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1535115320l/40121378.jpg',
    rating: 4.9,
    summary: 'An easy and proven way to build good habits and break bad ones. James Clear, an expert on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    comments: [],
    genre: 'Self-Help',
  },
  {
    id: 10,
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    coverImage: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1498123911l/32620332.jpg',
    rating: 4.7,
    summary: 'Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself.',
    comments: [],
    genre: 'Romance',
  }
];

export const mockGenres = ['Fiction', 'Science Fiction', 'Fantasy', 'Mystery', 'Thriller', 'Romance', 'Biography', 'History', 'Self-Help'];
